blo/urls.py
from django.urls import path
from . import views

app_name = 'blo'

urlpatterns = [
    path('',views.index, name='index'),
    path('create/', views.create, name='create'),
    path('account/', views.account, name='account'),
    path('blog/<int:id>/', views.blog, name='blog'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('edit/<int:id>/',views.edit,name='edit'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blo.urls'))
]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

blo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Category(models.Model):
    name = models.CharField(max_length=225)    

class Tag(models.Model):
    name = models.CharField(max_length=225)

class Blog(models.Model):
    title = models.CharField(max_length=225)
    description = models.TextField()
    date = models.DateField(auto_now=True)
    image =models.ImageField(upload_to='blogimg')
    description_big = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

blo/views.py
from django.shortcuts import render,redirect, reverse

from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from blo.models import Author, Category, Tag, Blog
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect




@login_required(login_url='login/')
def index(request):
    categories = Category.objects.all()
    tags = Tag.objects.all()
    authors = Author.objects.all()
    blogs = Blog.objects.all()

    context = {
        'categories': categories,
        'tags': tags,
        'authors': authors,
        'blogs': blogs,
    }
    return render(request, 'index.html', context=context)
    
@login_required(login_url='login/')
def create(request):
    user = request.user
    author = Author.objects.get(user=user)
    categories = Category.objects.all()
    if request.method == 'POST':
        title = request.POST.get('title')
        image = request.FILES.get('image')
        description = request.POST.get('description')
        category = request.POST.get('category')
        description_big = request.POST.get('description_big')
        category = Category.objects.get(id=category)

        blogs = Blog.objects.create(
             title=title,
             image=image,
             description=description,
             category=category,
             description_big=description_big,
             author=author,
        )
        blogs.save()

        context = {
            'categories': categories,
            'blogs': blogs,
        }
        return redirect('blo:index')
    else:        
        context = {
            'categories': categories,
        }
        return render(request, 'create.html', context=context)

@login_required(login_url='login/')
def account(request):
    user = request.user
    author = Author.objects.get(user=user)
    blogs = Blog.objects.filter(author=author)

    context = {
        'blogs': blogs,
    }
    return render(request, 'account.html',context=context)

@login_required(login_url='login/')
def edit(request,id):
    categories = Category.objects.all()
    blogs = Blog.objects.get(id=id)

    if request.method == 'POST':
        title = request.POST.get('title')
        image = request.FILES.get('image')
        description = request.POST.get('description')
        category = request.POST.get('category')
        description_big = request.POST.get('description_big')
        category = Category.objects.get(id=category)

        title=title,
        image=image,
        description=description,
        category=category,
        description_big=description_big,
        author=author,     

        blogs.save()

        context = {
            'categories': categories,
            'blogs': blogs,
        }
        return redirect('blo:account')
    else:        
        context = {
            'blogs': blogs,
        }
        return render(request, 'edit.html', context=context)

@login_required(login_url='login/')
def delete(request, id):
    blogs = Blog.objects.get(id=id)
    blogs.delete()
    return redirect('blo:account')

@login_required(login_url='login/')
def blog(request,id):
    blog = Blog.objects.get(id=id)
    context = {
        'blog': blog
    }

    return render(request, 'blog.html', context=context)   

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if user:
                auth_login(request, user)
                return redirect('blo:index')
            else:
                return render(request, 'login.html', {'error': 'Invalid username or password'})
    else:
        return render(request, 'login.html')    

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        
        if User.objects.filter(username=username).exists():
                return render(request, 'register.html', {'error': 'Username already exists'})
        else:
                user = User.objects.create_user(
                    username=username,
                    first_name=first_name,
                    last_name=last_name,
                    password=password,
                )

        author = Author.objects.create(
            user=user
        )
        return redirect('blo:login')  
    

    else:
        return render(request, 'register.html')

@login_required(login_url='/login')
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('blo:login'))

templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header>
        <section class="wrapper">
            <div class="left">
                <h1><a href="{% url 'blo:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a></h1>
            </div>
            <div class="middle">
                <form action="">
                    <div>
                        <input type="search" placeholder="Search blog...">
                        <img src="{% static 'images/search.png' %}" alt="search" />
                    </div>
                </form>
            </div>
            <div class="right">
                <ul>
                    <li><a href="{% url 'blo:index' %}">Home</a></li>
                    <li><a href="{% url 'blo:create' %}">Create</a></li>
                    <li><a href="{% url 'blo:account' %}">Account</a></li>
                </ul>
            </div>
        </section>
    </header>

    <section id="blog-list">
        <section class="wrapper">
            <div class="top">
                <h1>My Blogs</h1>
                <a href="#">Create</a>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Date</th>
                        <th>View</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for blog in blogs %}
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td><a href="{% url 'blo:blog' blog.id %}">{{blog.title}}</a></td>
                        <td>{{blog.date}}</td>
                        <td>
                            <a href="{% url 'blo:blog' blog.id %}" class="view">View</a>
                        </td>
                        <td>
                            <a href="{% url 'blo:edit' blog.id %}" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="{% url 'blo:delete' id=blog.id %}" class="delete">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <!-- <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{% static './images/blog.png' %}" alt="blog">
                        </td>
                        <td>Lorem ipsum dolor sit amet consectetur.</td>
                        <td>12 May 2023</td>
                        <td>
                            <a href="#" class="view">View</a>
                        </td>
                        <td>
                            <a href="#" class="edit">Edit</a>
                        </td>
                        <td>
                            <a href="#" class="delete">Delete</a>
                        </td>
                    </tr> -->
                </tbody>
            </table>
            <div class="bottom">
                <div class="pagination">
                    <a href="#" class="prev">
                        <img src="{% static 'images/left-arrow.png' %}" alt="prev">
                    </a>
                    <a href="#" class="active">1</a>
                    <a href="#">2</a>
                    <span>...</span>
                    <a href="#">7</a>
                    <a href="#">8</a>
                    <a href="#" class="next">
                        <img src="{% static 'images/right-arrow.png' %}" alt="next">
                    </a>
                </div>
            </div>
        </section>
    </section>


</body>
</html>

templates/bit.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <section id="pricing">
        <section class="wrapper">
            <div class="container">
                <div class="card">
                    <h3>Free</h3>
                    <h1>USD 0</h1>
                    <p>per user/month</p>
                    <span>upto 5 users</span>
                    <a href="">Get started</a>
                    <p>Free Forever</p>
                </div>
                <div class="card">
                    <h3>Standard</h3>
                    <h1>usd 3</h1>
                    <p>per user/month</p>
                    <span>1-500 users</span>
                    <a href="">Get started</a>
                    <p>Start at $15 /month</p>
                </div>
                <div class="card">
                    <h3>Premium</h3>
                    <h1>usd 3</h1>
                    <p>per user/month</p>
                    <span>1-500 users</span>
                    <a href="">Get started</a>
                    <p>Start at $30 /month</p>
                </div>
            </div>
        </section>
    </section>

</body>
</html>

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header>
        <section class="wrapper">
            <div class="left">
                <h1><a href="index.html"><img src="images/logo.png" alt="logo"></a></h1>
            </div>
            <div class="middle">
                <form action="">
                    <div>
                        <input type="search" placeholder="Search blog...">
                        <img src="{% static 'images/search.png' %}" alt="search" />
                    </div>
                </form>
            </div>
            <div class="right">
                <ul>
                    <li><a href="{% url 'blo:index' %}">Home</a></li>
                    <li><a href="{% url 'blo:create' %}">Create</a></li>
                    <li><a href="{% url 'blo:account' %}">Account</a></li> 
                </ul>
            </div>
        </section>
    </header>

    <section id="blog-details">
        <section class="wrapper">
            <div class="left">
                <h1>{{ blog.title }}.</h1>
                <p>{{ blog.description }}.</p>
                <div>
                    <p>{{ blog.author.user.first_name }} {{ blog.author.user.last_name }}</p>
                    <p>{{ blog.date }}</p>
                </div>
                <img src="{{ blog.image.url }}" alt="blog">
                <p>{{ blog.description_big }}</p>
            </div>
            <div class="right">
                <h3>Recent Blogs</h3>
                <div>
                    <img src="{% static 'images/blog.png' %}" alt="blog">
                    <a href="blog.html">
                        <h3>Lorem ipsum dolor sit amet consectetur.</h3>
                    </a>
                </div>
                <div>
                    <img src="{% static 'images/blog.png' %}" alt="blog">
                    <a href="blog.html">
                        <h3>Lorem ipsum dolor sit amet consectetur.</h3>
                    </a>
                </div>
                <div>
                    <img src="{% static 'images/blog.png' %}" alt="blog">
                    <a href="blog.html">
                        <h3>Lorem ipsum dolor sit amet consectetur.</h3>
                    </a>
                </div>
                <div>
                    <img src="{% static 'images/blog.png' %}" alt="blog">
                    <a href="blog.html">
                        <h3>Lorem ipsum dolor sit amet consectetur.</h3>
                    </a>
                </div>
                <div>
                    <img src="{% static 'images/blog.png' %}" alt="blog">
                    <a href="blog.html">
                        <h3>Lorem ipsum dolor sit amet consectetur.</h3>
                    </a>
                </div>
            </div>
        </section>
    </section>


</body>
</html>

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header>
        <section class="wrapper">
            <div class="left">
                <h1><a href="{% url 'blo:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a></h1>
            </div>
            <div class="middle">
                <form action="">
                    <div>
                        <input type="search" placeholder="Search blog...">
                        <img src="{% static 'images/search.png' %}" alt="search" />
                    </div>
                </form>
            </div>
            <div class="right">
                <ul>
                    <li><a href="{% url 'blo:index' %}">Home</a></li>
                    <li><a href="{% url 'blo:create' %}">Create</a></li>
                    <li><a href="{% url 'blo:account' %}">Account</a></li>
                </ul>
            </div>
        </section>
    </header>

    <section id="create">
        <section class="wrapper">
            <h1>Create a new blog</h1>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-control">
                    <input type="text" placeholder="Enter title" name="title">
                </div>
                <div class="form-control">
                    <label for="blog-image">Featured Image:</label>
                    <input type="file" name="image">
                </div>
                <div class="form-control">
                    <input type="text" placeholder="Enter short description" name="description">
                </div>
                <div class="form-control">
                    <select name="category" id="">
                        {% for category in categories %}
                        <option value="{{category.id}}">{{category.name}}</option>
                        <!-- <option value="Technology">Technology</option>
                        <option value="Health">Health</option> -->
                        {% endfor %}
                    </select>
                </div>
                <!-- <div class="form-control">
                    <input type="text" placeholder="Enter tags (seperate using comma)" name="tags">
                </div> -->
                <div class="form-control">
                    <textarea name="description_big" id="" cols="30" rows="10" placeholder="Enter blog"></textarea>
                </div>
                <div class="btn">
                    <input type="submit" value="Create">
                </div>
            </form>
        </section>
    </section>


</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="images/icon.png" type="image/x-icon">
    <title>Blogger</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    <header>
        <section class="wrapper">
            <div class="left">
                <h1><a href="{% url 'blo:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a></h1>
            </div>
            <div class="middle">
                <form action="">
                    <div>
                        <input type="search" placeholder="Search blog...">
                        <img src="{% static 'images/search.png' %}" alt="search" />
                    </div>
                </form>
            </div>
            <div class="right">
                <ul>
                    <li><a href="{% url 'blo:index' %}">Home</a></li>
                    <li><a href="{% url 'blo:create' %}">Create</a></li>
                    <li><a href="{% url 'blo:logout' %}" class="font-semibold">Logout</a></li>
                    <li><a href="{% url 'blo:account' %}">Account</a></li>
                </ul>
            </div>
        </section>
    </header>

    <section id="category">
        <section class="wrapper">
            <ul>
                {% for category in categories %}
                <li><a class="active" href="#">{{category.name}}</a></li>
                {% endfor %}
            </ul>
        </section>
    </section>

    <section id="blogs">
        <section class="wrapper">
            <div class="left">
                <div class="top">
                    {% for blog in blogs %}
                    <div class="card">
                        <img src="{{blog.image.url}}" alt="blog-image">
                        <h3>
                            <a href="{% url 'blo:blog' blog.id %}">{{blog.title}}</a>
                        </h3>
                        <div>
                            <span>{{blog.author.user.first_name}} {{blog.author.user.last_name}}</span>
                            <span>{{blog.date}}</span>
                        </div>
                        <p>{{blog.description}}</p>
                        <ul>
                            {% for tag in blog.tags.all %}
                            <li>{{tag.name}}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}
                    <!-- <div class="card">
                        <img src="{% static 'images/blog.png' %}" alt="blog-image">
                        <h3>
                            <a href="blog.html">Lorem ipsum dolor sit.</a>
                        </h3>
                        <div>
                            <span>Adil CP</span>
                            <span>20 May 2023</span>
                        </div>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet voluptate deleniti placeat consectetur optio facere. Expedita, nobis? Minus, numquam harum.</p>
                        <ul>
                            <li>Food</li>
                            <li>Healthy</li>
                            <li>Spicy</li>
                            <li>Lorem</li>
                            <li>Spicy</li>
                            <li>Spicy</li>
                        </ul>
                    </div>
                    <div class="card">
                        <img src="{% static 'images/blog.png' %}" alt="blog-image">
                        <h3>
                            <a href="blog.html">Lorem ipsum dolor sit.</a>
                        </h3>
                        <div>
                            <span>Adil CP</span>
                            <span>20 May 2023</span>
                        </div>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet voluptate deleniti placeat consectetur optio facere. Expedita, nobis? Minus, numquam harum.</p>
                        <ul>
                            <li>Food</li>
                            <li>Healthy</li>
                            <li>Spicy</li>
                            <li>Lorem</li>
                            <li>Spicy</li>
                            <li>Spicy</li>
                        </ul>
                    </div>
                    <div class="card">
                        <img src="{% static 'images/blog.png' %}" alt="blog-image">
                        <h3>
                            <a href="blog.html">Lorem ipsum dolor sit.</a>
                        </h3>
                        <div>
                            <span>Adil CP</span>
                            <span>20 May 2023</span>
                        </div>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet voluptate deleniti placeat consectetur optio facere. Expedita, nobis? Minus, numquam harum.</p>
                        <ul>
                            <li>Food</li>
                            <li>Healthy</li>
                            <li>Spicy</li>
                            <li>Lorem</li>
                            <li>Spicy</li>
                            <li>Spicy</li>
                        </ul>
                    </div>
                    <div class="card">
                        <img src="{% static 'images/blog.png' %}" alt="blog-image">
                        <h3>
                            <a href="blog.html">Lorem ipsum dolor sit.</a>
                        </h3>
                        <div>
                            <span>Adil CP</span>
                            <span>20 May 2023</span>
                        </div>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet voluptate deleniti placeat consectetur optio facere. Expedita, nobis? Minus, numquam harum.</p>
                        <ul>
                            <li>Food</li>
                            <li>Healthy</li>
                            <li>Spicy</li>
                            <li>Lorem</li>
                            <li>Spicy</li>
                            <li>Spicy</li>
                        </ul>
                    </div> -->
                </div>
                <div class="bottom">
                    <div class="pagination">
                        <a href="#" class="prev">
                            <img src="{% static 'images/left-arrow.png' %}" alt="prev">
                        </a>
                        <a href="#" class="active">1</a>
                        <a href="#">2</a>
                        <span>...</span>
                        <a href="#">7</a>
                        <a href="#">8</a>
                        <a href="#" class="next">
                            <img src="{% static 'images/right-arrow.png' %}" alt="next">
                        </a>
                    </div>
                </div>
            </div>

            <div class="right">
                <h1>Fiter Blogs</h1>
                <form action="">
                    <div class="sort">
                        <h3>Sort by</h3>
                        <div>
                            <input type="radio" name="" id="">
                            <span>Recently Added</span>
                        </div>
                        <div>
                            <input type="radio" name="" id="">
                            <span>A-Z Ascending</span>
                        </div>
                        <div>
                            <input type="radio" name="" id="">
                            <span>A-Z Descending</span>
                        </div>
                    </div>
                    <div class="author">
                        <h3>By Author</h3>
                        {% for author in authors %}
                        <div>
                            <input type="checkbox" name="" id="">
                            <span>{{author.user.first_name}} {{author.user.last_name}}</span>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="tags">
                        <h3>By Tags</h3>
                        {% for tag in tags %}
                        <div>
                            <input type="checkbox" name="" id="">
                            <span>{{tag.name}}</span>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="submit">
                        <input type="submit" value="Filter">
                    </div>
                </form>
            </div>
        </section>
    </section>
    
</body>
</html>